### ISSUE TITLE
Full architecture diagram with all mapped resources and Account wise and Role wise AWS resource distribution

### ISSUE THREAD

**Issue by tamaldatta91** [aws-solutions/workload-discovery-on-aws#113]
**Feature name**

- Account wise role should be created to restrict users viewing resources for their account only.

- There should be a feature to see full architecture diagram of all resources of an account.

**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like to see implemented**

- User role should be created. Users should be restricted to Account wise/ Role wise resource rather than implementing the same service in multiple accounts.

- We want to see a full architecture for all connected resources for an account. There should be option to check desired AWS services and Perspective will create a single connected diagram based on the selected resources.

**Describe the value this feature will add to AWS Perspective**
Tell us how this feature might improve AWS Perspective.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
