### ISSUE TITLE
Draw.io export to use layers to help NIST control classification e.g. networking, application, orchestration

### ISSUE THREAD

**Issue by datamystic** [aws-solutions/workload-discovery-on-aws#114]
**Feature name**
Architectural layers

**Is your feature request related to a problem? Please describe.**
When performing a NIST assessment, understanding the layers at which controls are applied is helpful for a complete assessment

**Describe the feature you'd like to see implemented**
Draw.io exports to classify components into layers. Layers can be enabled/disabled to show or hide detail

**Describe the value this feature will add to AWS Perspective**
This will increase the use cases that AWS Perspective adds value to

**Describe alternatives you've considered**
Manually moving resources to layers

**Additional context**

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
