### ISSUE TITLE
Networking layer to show data costs between VPCs, inbound/outbound

### ISSUE THREAD

**Issue by datamystic** [aws-solutions/workload-discovery-on-aws#115]
**Feature name**
Data cost allocation

**Is your feature request related to a problem? Please describe.**
Data costs have no home on the diagram, but may represent a significant part of the bill 

**Describe the feature you'd like to see implemented**
VPCs to display the cost of inbound and outbound data from the AWS bill

**Describe the value this feature will add to AWS Perspective**
To better reflect total cost of a solution

**Describe alternatives you've considered**
Manually adding from the bill

**Additional context**

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
