### ISSUE TITLE
Discovery process scanning message could be more verbose

### ISSUE THREAD

**Issue by spohle** [aws-solutions/workload-discovery-on-aws#117]
**Feature name**
Discovery verbosity

**Is your feature request related to a problem? Please describe.**
A description of what the problem is.

**Describe the feature you'd like to see implemented**
Currently the discovery process message only has a spinning circle. It would be great if there is some more info shown either directly in that message box, or somewhere else. Like what resource it is scanning currently, or if available how many resources are left to scan etc. Anything which shows the progress in some more detail would be great. As a user I want to have a better sense if it's still working than just the spinning circle.

**Describe the value this feature will add to AWS Perspective**
Better user experience

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
