### ISSUE TITLE
Remove costs

### ISSUE THREAD

**Issue by lcnatale** [aws-solutions/workload-discovery-on-aws#118]
**Feature name**
Remove costs.

**Is your feature request related to a problem? Please describe.**
Not a problem, but a usability issue. I have a CX that pays through a reseller Partner and no financial information should be disclosed to the CX.

**Describe the feature you'd like to see implemented**
The ability to deploy Perspective without financial information.

**Describe the value this feature will add to AWS Perspective**
Broadens the universe of CX's that would be able to use it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by svozza** [comment]
Hi there, the cost feature is disabled by default so those figures will just stay at $0.00 in the UI unless you specifically enable it.

**Comment by lcnatale** [comment]
Hi!
Ok, that’s a good starting point. I have not been able to try this. What about “removing the ability to enable” costs?

Thanks a lot!

--
Luciano Natale
Technical Account Manager | AWS Enterprise Support
email: lcnatale@amazon.copm.ar<mailto:lcnatale@amazon.copm.ar> · mobile: +54 911 5317-2623

 [signature_1765226552]
Thoughts on our interaction? Provide feedback here<https://feedback.aws.amazon.com/?ea=lcnatale&fn=Luciano&ln=Natale>.

**Comment by svozza** [comment]
Well to enable the feature you need to have access to the billing account, which the Cx would not not be able to do anyway?

**Comment by lcnatale** [comment]
That’s a good point!! Well I’ll give it a try this afternoon and see how it goes!
Thanks man!

--
Luciano Natale
Technical Account Manager | AWS Enterprise Support
email: lcnatale@amazon.copm.ar<mailto:lcnatale@amazon.copm.ar> · mobile: +54 911 5317-2623

 [signature_821116774]
Thoughts on our interaction? Provide feedback here<https://feedback.aws.amazon.com/?ea=lcnatale&fn=Luciano&ln=Natale>.

**Comment by svozza** [comment]
Good stuff, any other questions just give us a shout!
