### ISSUE TITLE
Be able to select multiple resources and indicate which resources have been selected

### ISSUE THREAD

**Issue by ju187** [aws-solutions/workload-discovery-on-aws#121]
**Feature name**
Resource multi-selection

**Is your feature request related to a problem? Please describe.**
Currently one could select one resource at a time and there is no indication one which one has be selected.  This makes creating a non-trivial diagram quite difficult

**Describe the feature you'd like to see implemented**
Provide the capability to select multiple resources at once and have indication on which ones have been selected

**Describe the value this feature will add to AWS Perspective**
Better userability

**Describe alternatives you've considered**
Drag-drop selection 

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by svozza** [comment]
This has come up before and here a few of the ideas we're thinking about: https://github.com/awslabs/aws-perspective/issues/31#issuecomment-698843928.

**Comment by svozza** [comment]
This was added in v1.1.0.
