### ISSUE TITLE
Add Elevation / Lenses - Highly Detailed -> Leadership View

### ISSUE THREAD

**Issue by jeff-s-burns** [aws-solutions/workload-discovery-on-aws#127]
Feature Name : Elevations - Standardized levels of detail

**Is your feature request related to a problem? Please describe.**
Convert raw data into information consumable by different audiences to support Business Cases, Design, Operations, Financials

**Describe the feature you'd like to see implemented**
The ability to change your perspective / elevation from the 10' (or 10m) level to the 100000' (or meter) level to accommodate different audiences. Examples:
1) Leadership - 100K' Elevation - Identify Cloud/VPC/Instance/Storage resources at a very course level and map to applications/URL's
2) Designer/Architecture - 20K' Elevation - Identify Leadership items but increased details to include connectivity. Include DNS/IP/Operating System Details
3) Engineer/Dev OPs - 10' Elevation, all of the gory details.  

Then business centric
1) Compliance Elevation
2) Security Elevation
3) Billing Elevation
 
**Describe the value this feature will add to AWS Perspective**
Increases audience for the data.  Permits usage of the data by leadership to create new AWS business. Use for business case justification / support of AWS servers and IT services.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
