### ISSUE TITLE
Integration with Security Hub / Guard Duty

### ISSUE THREAD

**Issue by steamatt** [aws-solutions/workload-discovery-on-aws#130]
**Feature name**
Perspectives Security Overlay

**Describe the feature you'd like to see implemented**
I would love to see Perspectives integrate with AWS Security Hub, and Guard Duty findings - the ability to have an architecture / infrastructure diagram with overlays showing you the highlighted Security Hub or Guard Duty Findings is a really powerful way for customers to be able to mitigate issues quickly.  If the reporting also included recommended fixes, that would enable customers to reduce their time diagnosing where a problem lies, and remediate.

**Describe the value this feature will add to AWS Perspective**
Highlighting security findings with best practice remediation provides a use case for AWS Perspective within the security teams of customers.

**Comment by svozza** [comment]
Yeah, this is definitely an avenue we want to explore and I think would complement what we already have very well.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
