### ISSUE TITLE
Auto discovery feature based on tag names

### ISSUE THREAD

**Issue by kandruch** [aws-solutions/workload-discovery-on-aws#139]
**Feature name**
Application AutoDiscovery

**Is your feature request related to a problem? Please describe.**
A description of what the problem is.

**Describe the feature you'd like to see implemented**
Need auto discovery feature based on tag names with all associated resources

**Describe the value this feature will add to AWS Perspective**
Having the ability to list a tag that is based on each of the resources an Application would be associated with would allow a desirable illustration of all the AWS services and costs in use for that App. This is also very handy for enterprise customers to ALWAYS have an updated illustrative diagram of their applications during internal discussions and processes without having to rely on outdated diagrams.

**Describe alternatives you've considered**
Workaround, can use tag editor to extract application tag and map the resources in AWS Perspective. This is a tedious process and error prone. It requires many manual steps and is not desirable.

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by svozza** [comment]
Are you talking about the ability to search by tag? That functionality already exists if that's what you're looking for:
<img width="729" alt="Screenshot 2021-04-13 at 13 07 59" src="https://user-images.githubusercontent.com/8573472/114550044-a9d0fc00-9c59-11eb-8e9d-6414b92ea757.png">

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
