### ISSUE TITLE
Create CloudFormation Template From Discovered Resources

### ISSUE THREAD

**Issue by matwerber1** [aws-solutions/workload-discovery-on-aws#14]
**Feature name**
CloudFormation template generation

**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like to see implemented**
Essentially, would love to see CloudFormer-like functionality integrated into AWS Perspective. AWS CloudFormer has been a "beta" project for 3 years, I don't think its actively developed... but conceptually, the idea is valuable for companies looking to migrate to infrastructure as code. A common ask from my customers is "how do I template-ize my existing infrastructure?" Yes, CloudFormation supports importing existing resources but its still a manual and tedious process. Would love to see this baked in somewhere. 

**Describe the value this feature will add to AWS Perspective**
Allow AWS Perspective to become an engine for adopting best practices (infra as code) and make it easier for customers to deploy new architecture (e.g. "cloning" resources, since they can now generate CF templates).

**Describe alternatives you've considered**
Alternatives boil down to manually writing CloudFormation, Terraform, CDK, etc. scripts when looking to adopt infra-as-code. 

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by PatMyron** [comment]
Recommend checking out https://github.com/iann0036/former2, as [CloudFormer is indeed no longer actively developed](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/439#issuecomment-611676438)
