### ISSUE TITLE
RBAC with saml

### ISSUE THREAD

**Issue by trtruong** [aws-solutions/workload-discovery-on-aws#142]
**Feature name**
granular RBAC

**Is your feature request related to a problem? Please describe.**
grant access to multiple teams and need to have granular access to per account/group of accounts base on each team.

**Describe the feature you'd like to see implemented**
RBAC that can assign to each individual or team, and possible using IAM role

**Describe the value this feature will add to AWS Perspective**
separate of accounts and responsibilites

**Comment by AntonyPotter** [comment]
This would be great.  We'd like to integrate Perspective with ADFS.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
