### ISSUE TITLE
filter resoures by tag

### ISSUE THREAD

**Issue by trtruong** [aws-solutions/workload-discovery-on-aws#143]
**Feature name**
filter resources by tag key:value

**Is your feature request related to a problem? Please describe.**
might reduce the number of resources needed to import in a region/account.  I've opened an issues related to large number of resources where discovery never finished.

**Describe the feature you'd like to see implemented**
getting a subset of resources from a particular region/account by on a tag key:value

**Describe the value this feature will add to AWS Perspective**
reduce workload on discovery
filter out unneeded resources.

**Comment by ims-swilkinson** [comment]
This would be extremely useful, it gives you a simple and extremely flexible way to filter what gets included.

**Comment by svozza** [comment]
You can already search by tag (the name of the tag is `tagName=tagValue` or do you have something else in mind?
<img width="910" alt="Screenshot 2022-10-31 at 15 08 50" src="https://user-images.githubusercontent.com/8573472/199041574-452fc262-87f9-44f0-8a84-8c80b6fd511b.png">

**Comment by ims-swilkinson** [comment]
No, I don't mean I'd like to include or exclude AWS::Tags::Tag resources.
I mean something different: I'd like to include any resource with a specific name-value pair in one of its tags.

For example, we have a tag named "service-name" on all of our resources which identifies which of our micro-services it is part of, and we'd like to include all resources with a specific value for the "service-name" tag. 
E.g. we might want to include any resource with the tag "service-name": "foo", which would include all resources for our "foo" service.

**Comment by svozza** [comment]
If, for example, you select the `Environment=dev` tag in the screenshot above and click `Add to diagram` it will add any resource that has that tag into a diagram.

**Comment by ims-swilkinson** [comment]
OK that's great! I didn't undertand the filter mechanism.

**Comment by svozza** [comment]
Yeah, sorry, I should have had the `Environment=dev` tag selected with the checkmark in the screenshot rather than the resource type tp make it more clear.
