### ISSUE TITLE
CloudWatch Metrics 

### ISSUE THREAD

**Issue by imtpalmer** [aws-solutions/workload-discovery-on-aws#149]
**Feature name**
Visualize Resource Utilization using CloudWatch metrics

**Is your feature request related to a problem? Please describe.**
It would very powerful if teams would quickly visualize the resource utilization signified with a color-coding or icon (Red=heavly used, Yellow=running hot, Green=optiomal, Blue=idle or underutilized)

**Describe the feature you'd like to see implemented**
For resources with CloudWatch metrics collect the past 30 days of performance metrics. (CPU, Memory, Disk/Network I/O). Offer a toggle to show or overlay the metrics onto the diagram. 
The detail tab would provide the aggregated data 
Offer the option which metric should be collected and displayed.

**Describe the value this feature will add to AWS Perspective**
Tell us how this feature might improve AWS Perspective.
Providing teams with the ability to rapidly see where over or underutilized resources exist in large complex infrastructure is incredibly powerful. Providing visibility into the overall infrastructure and seeing hot/or cold spots is crucial to understanding what dependencies exist and identifying opportunities for optimization.
**Note**: this feature would be beneficial with the ability to filter by tags.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.
There are a number of alternatives in the marketplace, but none provide a single view of the infrastructure with all of the relevant information in a diagram.

**Additional context**
Add any context or screenshots about the feature request here.
None available at this time.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
