### ISSUE TITLE
Filter by "At Risk" / "Needs Attention"

### ISSUE THREAD

**Issue by khan-asif** [aws-solutions/workload-discovery-on-aws#15]
**Feature name**
Advanced Filter

**Is your feature request related to a problem? Please describe.**
Currently the filter can only be done by Resource Type or Account-Region

**Describe the feature you'd like to see implemented**
Have advanced filter which is query based or at least with health state conditions

**Describe the value this feature will add to AWS Perspective**
It will provide a single window to check diagram, cost and systems at risk

**Describe alternatives you've considered**
Zoom In to see health icon which is not efficient

**Additional context**
N/A

**Comment by thebutler12** [comment]
This is a great idea, and fits closely to #6. If you haven't done so please upvote that enhancement as this will guide what features we work on.

**Comment by rakshb** [comment]
We've evaluated this request and added this to our backlog but it is not prioritized in the immediate roadmap for the solution.
