### ISSUE TITLE
Discovery process is scanning resources for 1 region for more than 11 hours. Debugged discovery component. Found status code 500

### ISSUE THREAD

**Issue by VC283940C** [aws-solutions/workload-discovery-on-aws#150]
{
    "detailedMessage": "Encountered a traverser that does not map to a value for child traversal: [GraphStep(vertex,[b3c96d305e802ce4a26266b2f1b53fa9])]",
    "requestId": "57fbb234-d12e-49c9-a895-9a1f94fcad03",
    "code": "IllegalArgumentException"
}
 (500)
    at Connection._handleMessage (/var/task/node_modules/gremlin/lib/driver/connection.js:282:9)
    at WebSocket.<anonymous> (/var/task/node_modules/gremlin/lib/driver/connection.js:130:43)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.EventEmitter.emit (domain.js:483:12)
    at Receiver.receiverOnMessage (/var/task/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.EventEmitter.emit (domain.js:483:12)
    at Receiver.dataMessage (/var/task/node_modules/ws/lib/receiver.js:413:14)
    at /var/task/node_modules/ws/lib/receiver.js:379:23
    at /var/task/node_modules/ws/lib/permessage-deflate.js:298:9 {
  statusCode: 500,
  statusMessage: '{"detailedMessage":"Encountered a traverser that does not map to a value for child traversal: [GraphStep(vertex,[b3c96d305e802ce4a26266b2f1b53fa9])]","requestId":"57fbb234-d12e-49c9-a895-9a1f94fcad03","code":"IllegalArgumentException"}',
  statusAttributes: {}
}

This is the last log stream for GremlinFunction. Found status code 500.
Discovery process is scanning resources for 1 region for more than 11 hours. Debugged discovery component. Found status code 500

Please guide as to what should be done to address this issue in discovery component and make it working

**Comment by svozza** [comment]
Hi there, apologies for the delay in response. I wouldn't worry about this error, this will not be why the discovery process in not working. Can you go to the logs for the Discovery process in the ECS console and see if there are errors in there. Remember, if you are posting log excerpts to redact any information like account numbers etc. Also, can you ensure that this is issue is not a problem: https://github.com/awslabs/aws-perspective/issues/98.
