### ISSUE TITLE
Want an API to export as PNG image

### ISSUE THREAD

**Issue by yo-saito** [aws-solutions/workload-discovery-on-aws#160]
**Feature name**
API to export as PNG image

**Is your feature request related to a problem? Please describe.**
We are considering the automatic creation of a configuration diagram using AWS Perspective. 
For example, we would like to automate the process of exporting the configuration diagram output from the AWS Perspective deployed in our own AWS account to PNG by searching for a specific tag.

**Describe the feature you'd like to see implemented**
API to export the output configuration diagram as PNG

**Describe the value this feature will add to AWS Perspective**
The API will expand the scope of automation.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by svozza** [comment]
This is a very good suggestion.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
