### ISSUE TITLE
Would like to add desired text under resources where we visualize the resources. 

### ISSUE THREAD

**Issue by mrlsdevops** [aws-solutions/workload-discovery-on-aws#161]
**Feature name**
 Add desired text under resources

**Is your feature request related to a problem? Please describe.**
At this point, we are not able to add any of text under resources as we don't see full resource name in the graph. For Instance, subnets names. we intended to add my desired text under resources  

**Describe the feature you'd like to see implemented**
Just wanted to make sure we are in position to add text value under resources 

**Describe the value this feature will add to AWS Perspective**
This feature will definitely add value to the perspective and everyone can able to add their desired text under resources. 

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
here is the sample snap after my expectations. where we can have editable field. so that we can enter my desired text under the resources. 

ex: subnets: 

![image](https://user-images.githubusercontent.com/39660674/118147892-0ac92c80-b3de-11eb-9916-5eda05ceb9ee.png)

**Comment by Klaudioz** [comment]
I'd love to have the option to add the EC2 instance name or a personalized text instead of the Instance ID.

**Comment by svozza** [comment]
Another thing we were thinking of is that if you've tagged your resource with a key called `Name` we could default to that.

**Comment by svozza** [comment]
As of v2.0.0, if Workload Discovery finds a tag with the key `Name` it will use that as the display name.
