### ISSUE TITLE
Should be able to deploy in existing vpc

### ISSUE THREAD

**Issue by rverma-nsl** [aws-solutions/workload-discovery-on-aws#169]
provide capability to deploy in existing vpc. Also wondering if we look as control tower architecture, this utility where should we deploy?
1. Shared Network Account
2. Shared services Account
3. Security and audit Account

**Comment by svozza** [comment]
Yes, this has come up before and is definitely something we want to do in the future.

**Comment by mhgrobert** [comment]
@svozza when can this be expected? Or is there documentation on editing the files to use your own?

**Comment by TheBigDog00** [comment]
Also interested in this. 
Can anyone point me to AWS documents that show this is NOT currently possible? 
Thanks!
-Roy

**Comment by paiyogis82** [comment]
My Customer is also interested in this , kindly confirm the timeline by when this will be available ?

**Comment by svozza** [comment]
Resolved by #383.
