### ISSUE TITLE
AWS Config Rule Compliance Overlay

### ISSUE THREAD

**Issue by EmpoweringSecurity** [aws-solutions/workload-discovery-on-aws#17]
**Feature name**
AWS Config Rule Compliance Overlay

**Is your feature request related to a problem? Please describe.**
Users want to view the current compliance of resources to help understand the environment visually where issues may lie with configuration.

**Describe the feature you'd like to see implemented**
The ability to turn off and on an visual indicator, maybe a red line or similar to quickly visualisally grasp non-compliant resources.

**Comment by thebutler12** [comment]
This is a great idea. 

I'm going to add your feedback to [this](https://github.com/awslabs/aws-perspective/issues/4) ticket as i think the two are related and close this one. Is that ok with you?

**Comment by svozza** [comment]
Also, if you upvote the issue Matt has linked to it will help us with prioritisation.

**Comment by rakshb** [comment]
We've evaluated this request and added this to our backlog but it is not prioritized in the immediate roadmap for the solution.
