### ISSUE TITLE
Transit Gateway for Distributed Accounts

### ISSUE THREAD

**Issue by ankitosh** [aws-solutions/workload-discovery-on-aws#175]
**Transit Gateway & Connectivity**
Give your feature a name.

**Is your feature request related to a problem? Please describe.**
unable to visualize the connectivity between the accounts

**Describe the feature you'd like to see implemented**
A description of what you would like to see.

**Describe the value this feature will add to AWS Perspective**
distributed account architecture view

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by svozza** [comment]
This has come up from customers before and I definitely think it would very useful!

**Comment by NetDevAutomate** [comment]
+1 This would be a hugely useful feature given the high prevalence for Transit Gateway.

**Comment by svozza** [comment]
Transit gateway and EKS resource types have been added to the solution in v2.0.0. Our upcoming v2.1.0 release will add support for cross account/VPC relationships between transit gateways.
