### ISSUE TITLE
Support for App Mesh Resources

### ISSUE THREAD

**Issue by kevinphillips81** [aws-solutions/workload-discovery-on-aws#179]
Feature name
App Mesh Support

Is your feature request related to a problem? Please describe.
The problem is that AWS Perspective does not give insights about the App Mesh architecture in AWS.

Describe the feature you'd like to see implemented
App Mesh Meshes, Gateways, Services, Routers, Nodes, etc. displayed in a nice manner.

Describe the value this feature will add to AWS Perspective
To be able to provide App Mesh architecture diagrams, and usage reporting

Describe alternatives you've considered
Manually putting everything together.

Additional context
None

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
