### ISSUE TITLE
Diagram creation and export API

### ISSUE THREAD

**Issue by grsr** [aws-solutions/workload-discovery-on-aws#180]
**Feature name**
Perspective diagram creating and export API

**Is your feature request related to a problem? Please describe.**
Currently creating an exporting diagrams is a manual process.

**Describe the feature you'd like to see implemented**
A mechanism to automatically create and export previously configured diagrams for use in electronic documentation, such as confluence.

**Describe the value this feature will add to AWS Perspective**
The requesting customer would like to automatically keep diagrams generate in Perspective and shared via other means up-to-date.

**Describe alternatives you've considered**
It might be possible to automate this with the existing UI with selenium scripts etc. but this seems brittle and error-prone.

**Comment by grsr** [comment]
This was a direct request from a customer considering deploying Perspective and comparing it with third-party offerings

**Comment by svozza** [comment]
We will be launching an SDK to allow programmatic access to the APIs that underlie the frontend: https://github.com/aws-solutions/workload-discovery-on-aws/pull/399.
