### ISSUE TITLE
Cost Report Time Period resets by error

### ISSUE THREAD

**Issue by an-echo** [aws-solutions/workload-discovery-on-aws#200]
**Describe the bug**
The Cost Report Time Period is reset when the CR is opened but the Summary is not.

**To Reproduce**

1. Go in cost report, change the time period to the previous month and submit
2. Close the Cost Report
3. Reopen the CR, the time period is back to the current month but the Summary displays le previous change (last month)

**Expected behavior**
The Time Period must stay aligned to the period used in the Summary otherwise it is misleading

**Screenshots**
n/a

**Browser (please complete the following information):**

Firefox 91.0.1

**Comment by thebutler12** [comment]
Hi,

Thanks for raising this. We are investigating the issue.

Cheers,

Matt
