### ISSUE TITLE
Want to create a VPC with a specific CIDR

### ISSUE THREAD

**Issue by kazu23pole** [aws-solutions/workload-discovery-on-aws#23]
**Feature name**
Want to create a VPC with a specific CIDR.

**Is your feature request related to a problem? Please describe.**
When you run CFn, a new VPC is automatically created and deployed to it.
Since the CIDR is fixed at 10.0.0.0/16, I want to deploy with a specific CIDR.

**Comment by svozza** [comment]
Hi there, thanks for the suggestion. This is definitely something we're looking at adding in a future release.

**Comment by jroedig** [comment]
Hey, next to that enhancement, it would be nice to use an already existing VPC as well. This will help if the organization does prevent creating VPCs via SCPs.

**Comment by svozza** [comment]
Yes, this is a good idea as well.

**Comment by lyx-daniela** [comment]
Hi all! May I check if anyone has found the solution to allow us to use an existing VPC for AWS Perspective please?

**Comment by svozza** [comment]
In the new release of WD (v2.1.0), you will be able to supply your own VPC so that can have whatever CIDR you want.
