### ISSUE TITLE
.png export does not respect manual placement of resources

### ISSUE THREAD

**Issue by pixarbuff** [aws-solutions/workload-discovery-on-aws#238]
**Describe the bug**
After manually arranging network elements in the grid view, exporting to .png ignores all positioning and reverts to original layout.

**To Reproduce**
1. Add elements to grid
2. arrange elements
3. export to .png
4. Open .png to find elements have reverted to their original positioning before step 2

**Expected behavior**
.png export should exactly match the position of elements on the screen at the moment of export.

**Screenshots**
![reverted](https://user-images.githubusercontent.com/43018109/149455723-0d100bc8-043f-4275-a6cb-2e4e5eb0de7b.png)
![arranged](https://user-images.githubusercontent.com/43018109/149455724-a212ef75-db53-4d33-bf82-52a064fb30e2.png)
**Browser (please complete the following information):**
- Chrome 97.0.4692.71

**Comment by EricSEkong** [comment]
Facing the same issue when attempting to export a diagram which was been grouped and filtered

**Comment by thebutler12** [comment]
Hey,

We are going to look into this. We are currently using the built-in functionality of Cytoscape to generate this. There may alternative libraries we could use to generate the PNGs.

**Comment by Klaudioz** [comment]
Happening the same to me and also when exporting to drawio.

**Comment by miketwenty1** [comment]
We would be interested in having the manual placement of these resources saved with the diagram if possible. Internal save and all exports will save/export under the default layout which can be pretty useless sometimes given the amount of resources displayed.

**Comment by carlosmonzon2008** [comment]
> Happening the same to me and also when exporting to drawio.

Yesterday I deployed "Workload Discovery v2.0.2". I don't see any option to export directly to PNG.
And using the option to export to "Diagrams.net", the elements appear misaligned, in different positions than shown in the web interface.

![image](https://user-images.githubusercontent.com/13509588/221804210-2c6d91b1-61f7-4f6d-9bd0-318279774194.png)

What I see in the Web interface.
![image](https://user-images.githubusercontent.com/13509588/221805584-ffefadd0-7e9c-410d-a7a4-6845c7860c41.png)

What I get in the exported diagram.
![image](https://user-images.githubusercontent.com/13509588/221806785-9f611724-6bc7-43e4-8af7-ffc6c2a53876.png)

**Comment by svozza** [comment]
Support for exporting to pngs was removed in v2.0.0.
