### ISSUE TITLE
Export All 

### ISSUE THREAD

**Issue by oland-codes** [aws-solutions/workload-discovery-on-aws#247]
**Feature name**
Export-All...The ability to obtain all discovered resources for a desired account/s

**Is your feature request related to a problem? Please describe.**
Net new functionality 

**Describe the feature you'd like to see implemented**
A table dump of all resources in a account

**Describe the value this feature will add to AWS Perspective**
This will great help when managing AWS Workload estates. Other cloud providers provide this offering.

**Describe alternatives you've considered**
ServiceNow CMDB should not be a pre-req to running AWS.

**Additional context**
Nope :)

**Comment by edschreibman** [comment]
+1 - Would be great to get flat file of everything discovered.  would not have to also deploy even [Prowler ](https://github.com/prowler-cloud/prowler )to export a file of all discovered resources.

**Comment by svozza** [comment]
In the meantime, you can use the paginated `getReources` GraphQL query added in v2.0.0 to get all the resources in the database.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog and has been prioritised on the roadmap for the solution.

**Comment by edschreibman** [comment]
> We've evaluated this request and added it to our backlog and has been prioritised on the roadmap for the solution.

:-)   thanks !
