### ISSUE TITLE
.png resolution for export

### ISSUE THREAD

**Issue by tmarsh** [aws-solutions/workload-discovery-on-aws#257]
**Feature name**
png resolution

**Is your feature request related to a problem? Please describe.**
A description of what the problem is.
When I export to a .png I am not able to read any of the resources as they are all blurry.

**Describe the feature you'd like to see implemented**
A description of what you would like to see.
Similar to draw.io be able to choose the dpi etc. to export as.

**Describe the value this feature will add to AWS Perspective**
Tell us how this feature might improve AWS Perspective.
Wouldn't have to export to draw.io and then export to .png

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.
Export to draw.io and then export from there as a .png etc. where you can choose the quality.

**Additional context**
Add any context or screenshots about the feature request here.
![blury_diagram](https://user-images.githubusercontent.com/771127/154378463-55e8fd1c-5fc0-4ddd-8a7a-6ad1bfbe5793.png)

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
