### ISSUE TITLE
Can't see any resources in perspective

### ISSUE THREAD

**Issue by co-pm** [aws-solutions/workload-discovery-on-aws#288]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
A description of what the bug is.

**To Reproduce**

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

**Comment by svozza** [comment]
Have you installed the `global` and `regional` CloudFormation templates in the account you want to import?
