### ISSUE TITLE
Resource Change Notifications

### ISSUE THREAD

**Issue by thebutler12** [aws-solutions/workload-discovery-on-aws#3]
AWS Perspective uses AWS Config to collect data about the AWS resources within your accounts and regions. It currently queries AWS Config at regular intervals to keep track of what is changing within discoverable accounts. We would like to move away from the pull approach and towards a push mechanism. This would involve integrating with AWS Config Events. Perspective would do an initial scan using AWS Config on deployment and importing of new accounts and regions. It will then react to AWS Config Events to ensure our data set it kept up to date with the changes you are making. We propose the following:

* Implement notifications based on AWS Config Events, letting you configure when you will be notified of changes to particular resources or resource types. These will be clickable, so you can see related resources.
* Remove the need to run the discovery process at regular intervals, as we will react to changes sent via AWS Config Events. 
* Automatically update your architecture diagrams whenever a resource within it changes.

**Comment by rakshb** [comment]
We evaluated this request and it is not prioritized in the immediate roadmap for the solution.
