### ISSUE TITLE
Support for additional networking components

### ISSUE THREAD

**Issue by avanbecelaere** [aws-solutions/workload-discovery-on-aws#302]
**Feature name**
Support for additional networking components

**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like to see implemented**
I would like to add support for the following networking resources:

- transit gateways
- transit gateway attachments
- transit gateway route tables
- internet gateways
- nat gateways
- vpc peering connections
- vpc/subnet route tables

Create network architecture / data flow diagrams for multi-account organizations.

**Describe the value this feature will add to AWS Perspective**
Create network architecture / data flow diagrams for multi-account organizations.

**Describe alternatives you've considered**
Lucidchart, CloudCraft

**Additional context**
None

**Comment by svozza** [comment]
Transit gateway and EKS resource types have been added to the solution in v2.0.0. Our upcoming v2.1.0 release will add support for cross account/VPC relationships between transit gateways.
