### ISSUE TITLE
move Perspective to new VPC

### ISSUE THREAD

**Issue by johnson-gr** [aws-solutions/workload-discovery-on-aws#305]
**Feature name**
Move AWS Perspective components to new VPC

**Is your feature request related to a problem? Please describe.**
To fix conflicting CIDR between regions and accounts , we like to create a new vpc and move AWS Perspective / Open Search Domain / Neptune database and all security groups to a new vpc.  Any process for this?

**Describe the feature you'd like to see implemented**
VPC move feature or process to move to a new VPC instead of deleting and rerunning cloudformation template

**Describe the value this feature will add to AWS Perspective**
We wont have to recreate users and re-setup filter settings etc

**Describe alternatives you've considered**
Manually  copying security groups to a new vpc and just moving the Opensearch Domain and Neptune database.  Not sure if that's everything

**Additional context**
AWS IPAM , conflicting CIDR so needing to make configuration changes

**Comment by svozza** [comment]
The filters and users are not stored in the database so you are probably just better off backing up the Cognito user pool (I've used this before https://www.npmjs.com/package/cognito-backup-restore), the `aws-perspective-amplifystoragebucket-*` where the filters are stored and the `aws-perspective-<account-id>-<region>-AppSyncApiStack-*-PerspectiveSettingsTable-*` DynamoDB table where the list of imported accounts are. Then do a fresh install and restore the items you saved to the newly create user pool/S3 bucket/DynaoDB table.

**Comment by svozza** [comment]
Bringing your own VPC will be address by #169 so we will track this in the original issue.
