### ISSUE TITLE
Expansion Icon to avoid expansion clicks if there is nothing to expand

### ISSUE THREAD

**Issue by ArlindNocaj** [aws-solutions/workload-discovery-on-aws#306]
**Feature name**
Expansion Icon

**Is your feature request related to a problem? Please describe.**

Many times when you expand the items, there is no additional resources being shown and you just loose time to click and expand a resource and wait until zooming is finished. If there would be an icon indicating how many expansionable items are behind a node you could easily just expand the nodes where there is something to expand.

**Describe the feature you'd like to see implemented**
A description of what you would like to see.
An icon showing a number of neighbours to the particular nodes which are currently not expaned.

**Describe the value this feature will add to AWS Perspective**
Tell us how this feature might improve AWS Perspective.
Much faster usage to expand to the architecture/resources you need.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
