### ISSUE TITLE
Add Cloudtrail relationships between roles and resources

### ISSUE THREAD

**Issue by ArlindNocaj** [aws-solutions/workload-discovery-on-aws#307]
**Feature name**
Cloudtrail relationships

**Is your feature request related to a problem? Please describe.**
A description of what the problem is.
The customer wants to use AWS Perspective to discover the dependencies of the resources. 
Cloudtrail logs contain a lot of information on which role has been accessing a particular service, e.g. S3: GetObject on bucket_xyz.

The role is typically visible in the cloudtrail logs and an be used to create a relationship between the role and the access of a particular bucket, e.g. role_s3_access -> s3:bucket_xyz

**Describe the feature you'd like to see implemented**
A description of what you would like to see.
Expanding a specific role resource would also show the links to the particular resources the role was interacting through the AWS platform based on the cloudtrail logs.

**Describe the value this feature will add to AWS Perspective**
Tell us how this feature might improve AWS Perspective.
This would allow to understand the interactions a particular role is using to specific resources and let the customer identify these additional dependencies to modernize applications.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
