### ISSUE TITLE
Instead of Arn how to publish name of resources

### ISSUE THREAD

**Issue by harishkrs** [aws-solutions/workload-discovery-on-aws#330]
**Feature name**
Tag name or resource name of resources should be displayed

**Is your feature request related to a problem? Please describe.**
ARN names are very big and seems like all of them looks like same, hence difficult to recognise the resources.

**Describe the feature you'd like to see implemented**
Tag name or resource name can be checked. Along with if grouping can be done on basis of tags.

**Describe the value this feature will add to AWS Perspective**
This will be helpful to better view the architecture.

**Describe alternatives you've considered**
Not yet

**Additional context**
Not applicable.

**Comment by svozza** [comment]
I might be misunderstanding, but if the discovery process finds a `Name` tag it will use that when displaying.

Here are the tags for an Internet Gateway in my account:
<img width="623" alt="Screenshot 2022-12-02 at 09 40 40" src="https://user-images.githubusercontent.com/8573472/205263823-d14eb6d5-b16f-4145-8fd8-f62bd4e10175.png">

Here is how it is displayed in the UI:
<img width="640" alt="Screenshot 2022-12-02 at 09 42 00" src="https://user-images.githubusercontent.com/8573472/205263836-75d9c1d7-8d91-4d8f-b80f-cd8482ac1392.png">

**Comment by citylineclark** [comment]
from my charts, vpc and subnets do not show the name .. it would be great if they can show the names for those resource types as well

**Comment by svozza** [comment]
This will be fixed in v2.1.0.

**Comment by svozza** [comment]
This was added in v2.1.0.
