### ISSUE TITLE
Export to JSON not working

### ISSUE THREAD

**Issue by jwesley235** [aws-solutions/workload-discovery-on-aws#336]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
When I select the JSON radio button and click 'Export,' nothing happens. A look at the console shows this error: "react-dom.production.min.js:101 Uncaught TypeError: e.nodes is not a function
    at CreateJSONExport.js:2:24
    at onClick (ExportDiagram.js:50:18)
    at vv (index.ts:71:3)
    at internal.tsx:72:9
    at Object.He (react-dom.production.min.js:52:317)
    at Xe (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Tr (react-dom.production.min.js:100:68)
    at Ir (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65."

**To Reproduce**
, ,' , .'

1. Create or open a diagram
2. click on 'Diagram>Export
3. select JSON
4. click on 'Export
5. Open console to see error

**Expected behavior**
A JSON file should be generated

**Screenshots**
<img width="541" alt="Screen Shot 2022-12-07 at 10 39 05 AM" src="https://user-images.githubusercontent.com/72158438/206267769-fefe3dbf-8831-442c-92ad-446feead238a.png">

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]
Chrome
Version 107.0.5304.121 (Official Build) (arm64)
**Additional context**

**Comment by svozza** [comment]
fixed by #384
