### ISSUE TITLE
User experience

### ISSUE THREAD

**Issue by TJarriault** [aws-solutions/workload-discovery-on-aws#34]
**Feature name**
Application VIEW

**Is your feature request related to a problem? Please describe.**
As a user, i want to have a resume of my applications deployed on my account

**Describe the feature you'd like to see implemented**
As a user, i want to choose on the dashboard some (filters) to simply modify view depending of the filter selection.
I want to zoom or not the view (like BI tool).
The capacity to generate global report of the architecture will be very usefull for architect guys.

**Describe the value this feature will add to AWS Perspective**
The solution will be more easier to use if you add filters menu on the dashbord and the capacity (+ / -) on the dashboard.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by thebutler12** [comment]
Hey, thanks for the feedback. It sounds quite close to the Dashboard feature that is mentioned in #5, if you haven't already upvoted it please do as that will guide the features we work. 

Regarding "and the capacity (+ / -) on the dashboard.", would you like to see diagram controls like zooming and panning available using a separate control component as well as using mouse/trackpad?

**Comment by rakshb** [comment]
We've evaluated this request and added this to our backlog but it is not prioritized in the immediate roadmap for the solution.
