### ISSUE TITLE
workload discovery for the us gov cloud

### ISSUE THREAD

**Issue by bebemaz** [aws-solutions/workload-discovery-on-aws#380]
I see there is a template for all the regions except the US GOV cloud. Does anyone have one ? Or how would I modify the templates for the other regions to suit the govcloud region?

**Comment by svozza** [comment]
The GovCloud region does not yet support AppSync. This service helps provide all our APIs so there is no workaround that will make the tool work if this service is not present in the region.

**Comment by svozza** [comment]
I'm presume SAAS offerings are not an option because of security concerns so you could try this self hosted solution: https://www.cloudgraph.dev/.

**Comment by svozza** [comment]
Closing this as there's nothing we can do about AppSync availability in GovCloud.
