### ISSUE TITLE
Highlight Resource Compliance Status

### ISSUE THREAD

**Issue by thebutler12** [aws-solutions/workload-discovery-on-aws#4]
We would include AWS Config Rules data as part of our discovery process. This will let us highlight resources in your architecture diagrams that are noncompliant. We would also provide a menu with AWS Config Rules that are active across your accounts so you can see the individual resources that are noncompliant. We propose the following:

* Highlight resource in architecture diagrams that will indicate noncompliance to AWS Config Rules.
* A link to the the AWS Config Rule in the ‘Show Details’ dialog. 
* A new side panel menu that displays all active AWS Config Rules and the resources that are noncompliant.

**Comment by thebutler12** [comment]
Feedback from @EmpoweringSecurity

Feature name
AWS Config Rule Compliance Overlay

Is your feature request related to a problem? Please describe.
Users want to view the current compliance of resources to help understand the environment visually where issues may lie with configuration.

Describe the feature you'd like to see implemented
The ability to turn off and on an visual indicator, maybe a red line or similar to quickly visualisally grasp non-compliant resources.

**Comment by cool-raj** [comment]
+1

**Comment by rakshb** [comment]
We've evaluated this request and added this to our backlog but it is not prioritized in the immediate roadmap for the solution.
