### ISSUE TITLE
CSV report of the Resources does not include ARN

### ISSUE THREAD

**Issue by sckrish** [aws-solutions/workload-discovery-on-aws#407]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
CSV report of the Resources does not include ARN

**To Reproduce**

1. Go to '.Workload Discovery'
2. Click on 'Diagrams'
3. Scroll down to 'Export to CSV.'
4. The ARN values will not appear on the CSV

**Expected behavior**
The CSV values should appear
[EC2-tag.csv](https://github.com/aws-solutions/workload-discovery-on-aws/files/11173043/EC2-tag.csv)
[Tag-02-App002139.csv](https://github.com/aws-solutions/workload-discovery-on-aws/files/11173044/Tag-02-App002139.csv)

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

**Comment by svozza** [comment]
This will be fixed in v2.1.0.
