### ISSUE TITLE
Runtime.ImportModuleError: Unable to import module 'cleanup_bucket'

### ISSUE THREAD

**Issue by ankith01** [aws-solutions/workload-discovery-on-aws#424]
Hi Team, after run multiple times and there is openSSL issue and tested with diff. OS but still it's same issue while creating "S3Buckets" stack CF. looks like it's openssl issue which is out dated on the code. pls share next steps.

--------------------------------
[ERROR] Runtime.ImportModuleError: Unable to import module 'cleanup_bucket': urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168
Traceback (most recent call last):
----------------------------------

**Comment by tmekari** [comment]
Thank you for bringing this to our attention, this will be fixed in our upcoming release. In the meantime, can you please provide steps to reproduce this error so I can help you with this issue?
