### ISSUE TITLE
EMR cluster discovery and visualization.

### ISSUE THREAD

**Issue by BigDataDaddy** [aws-solutions/workload-discovery-on-aws#43]
**Feature name**
EMR cluster discovery and vizualization.

**Is your feature request related to a problem? Please describe.**
I'd like to be able to visualize EMR clusters and their relationships to other discovered resources, like VPC, Route53, S3, Glue Data Catalog, and other resources,

**Describe the feature you'd like to see implemented**
Discovery and rendering in diagrams just like the existing resources.

**Describe the value this feature will add to AWS Perspective**
This feature will make AWS Perspective usable by customers that are primarily using the AWS big data stack and specifically using EMR for data ingestion and pipeline processing.

**Describe alternatives you've considered**
We've looked 10's of commercial and open source product that do AWS resource visualization and they all fall short in 1 or 2 specific areas of keen interest to analytics and big data stack AWS customers:
1. Visualizing the big data stack service resource, like Redshift and EMR.
2. Completely visualizing the networking components of VPC, including VPCs, subnets, all gateways, ELBs, and connecting resources.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
