### ISSUE TITLE
Select all resources with tag and/or multi select in search

### ISSUE THREAD

**Issue by ycrc5** [aws-solutions/workload-discovery-on-aws#444]
**Feature name**
Select all resources with tag and/or multi select in search

**Is your feature request related to a problem? Please describe.**
We have over 16 000 resources in our account and would like to build up diagrams for all the resources. Adding them 1 by 1 is tedious and takes a fair amount of time.

**Describe the feature you'd like to see implemented**
There are 2 features that I would love to see added.

First, be able to have a way to include all resources with the tag value of "x". For example, lets say we have an application built with Lambda, DynamoDB and IAM. Each of these resources is tagged with application-name:foo . In this example, if we can select all resources with tag application-name = foo that would be awesome.

The second is to have the ability to multi select in the search when creating a diagram. The aim is similiar to the above to make it easier and faster to add services.

**Describe the value this feature will add to AWS Perspective**
I believe this feature has great value enhancing the applications proposition by making it easier to generate graphs. We make heavy usage of tags and we can manage them through IaC.

**Describe alternatives you've considered**
Both listed above.

**Additional context**
N/A

**Comment by ycrc5** [comment]
I do see some tags come up in the search, but not all and don't know what the requirement is to get them to show. Perhaps this feature exists, just need to do something about the tags?

**Comment by svozza** [comment]
Tags are stored with the name `${key}=${value}` so if you filter resources by the `AWS::Tags::Tag` resource type and search for the string `application=foo` then that should find the tag. Bear in mind though that this search is retrieved from OpenSearch meaning the match is fuzzy so you may have some extra results lower down too. Also, tags are saved on a per account basis so you may see multiple versions of the same tag.

<img width="697" alt="Screenshot 2023-07-28 at 10 25 22" src="https://github.com/aws-solutions/workload-discovery-on-aws/assets/8573472/02db934e-dd92-492f-a99d-49b95f5c6eb4">
wer down.

**Comment by ycrc5** [comment]
Thanks @svozza . Digging into the tags, it looks like one of the culprits is that CloudFormation does not yet support tagging on event bridge rules [link](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/358). But this is an issue with CloudFormation. Ill need to find another way to easily find the resources if tagging is not an option.

I will close this for now, but have 1 last question. Regarding the open search indexing, is it possible to have an advanced mode to have more control on the search? So find anything that starts with xxxx ?

**Comment by svozza** [comment]
Yeah, I would definitely like to give more control over search and also your multiselect idea is also something that I think would be a very nice improvement.
