### ISSUE TITLE
unsupported operand type(s) for *: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by speedydreser** [aws-solutions/workload-discovery-on-aws#458]
I am currently having problems when exporting a diagram to Drawio I get the following error:
unsupported operand type(s) for *: 'NoneType' and 'float'

And I have not been able to find the origin of said [err](url)

**Comment by svozza** [comment]
What version of the solution are you using? We did add a fix to this for the new version (2.1.0) released a few weeks ago.

**Comment by lajtosadam** [comment]
I use a Version: v2.1.0, but i have the same issue.

**Comment by speedydreser** [comment]
I use a  Version: v2.0.3.

**Comment by svozza** [comment]
So it looks like the fix released in v2.1.0 only partially fixed this bug. We will have to investigate what other edge cases are causing the problem.

**Comment by omri-shilton** [comment]
any updates on this issue?

**Comment by svozza** [comment]
@JacobReynolds is correct and so is the fix posted. I have tidied up the lambda function a bit and added steps on how to patch in this [comment](https://github.com/aws-solutions/workload-discovery-on-aws/issues/509#issuecomment-1934666948).

**Comment by svozza** [comment]
This was fixed in v2.1.6.
