### ISSUE TITLE
Wider region support

### ISSUE THREAD

**Issue by mohsanjaffery** [aws-solutions/workload-discovery-on-aws#47]
**Feature name**
Wider region support

**Is your feature request related to a problem? Please describe.**
AWS Perspective does not work in China Regions due to a lack of support for Amazon Cognito

**Describe the feature you'd like to see implemented**
An alternative implementation of AuthN/AuthZ which does not require Amazon Cognito

**Describe the value this feature will add to AWS Perspective**
Increased usage of AWS Perspective across China and other regions that have limited Amazon Cognito support

**Comment by svozza** [comment]
We evaluated this request and it is not prioritised in the immediate roadmap for the solution.
