### ISSUE TITLE
what is the ⚠️ in top-right corner of instance icon indicative of?

### ISSUE THREAD

**Issue by BogdanSorlea** [aws-solutions/workload-discovery-on-aws#483]
LE: added bug information to it, see [comment below](https://github.com/aws-solutions/workload-discovery-on-aws/issues/483#issuecomment-1782557414)

Sorry if I'm too blunt. It's driving me crazy and can't seem to find much info about it. Help? :D

![Screenshot 2023-10-25 at 15 52 31](https://github.com/aws-solutions/workload-discovery-on-aws/assets/4004804/07d9d42d-0662-49e5-bb5a-89cc2568e1bd)

**Comment by svozza** [comment]
From reading the code it means the instance state is in one these states, `creating`, `pending`, or `provisioning`:

https://github.com/aws-solutions/workload-discovery-on-aws/blob/ef4c6b16066d537fe210fe9da12678c6e9c5dc93/source/frontend/src/Utils/Resources/ResourceStateParser.js#L24C5-L24C5

**Comment by BogdanSorlea** [comment]
I didn't really have time to run through the code (also not very clear about its structure, etc), but definitely thanks for the heads up, @svozza 

what's interesting about them is that they have been in a running state since Oct 3 / Oct 10 / Oct 25, yet all three of them have the icon - I find that to be inconsistent
![Screenshot 2023-10-26 at 10 22 25](https://github.com/aws-solutions/workload-discovery-on-aws/assets/4004804/f889a735-5721-478e-a576-136854417fdc)

I'll look through the code some more, but if anyone has any idea what might be going on, I'd love to hear about it. Thanks :D

**Comment by BogdanSorlea** [comment]
same for the database - and that one has been running on since "forever"
![Screenshot 2023-10-26 at 10 38 13](https://github.com/aws-solutions/workload-discovery-on-aws/assets/4004804/1d194df0-cf4a-4c8d-9aa8-89e4ce0bdf3d)

**Comment by BogdanSorlea** [comment]
Load Balancers of both network and application type seem to have it too.
![Uploading Screenshot 2023-10-26 at 13.34.16.png…]()

**Comment by BogdanSorlea** [comment]
so I'm either doing something wrong or there is a bug somewhere if this is unexpected behaviour. Probably the former, but what could it be?!

**Comment by svozza** [comment]
Looks like this might be a bug to me.

**Comment by BogdanSorlea** [comment]
adding bug information below

**Describe the bug**
EC2 instance, RDS instance, ELB icons all have a ⚠️ sign next to them although they're all running and have been running for a long time (are not in a different state than running).

**To Reproduce**
Steps to reproduce the behavior:

unsure how to fully reproduce, as I am running against an already-existing set of resources, but maybe:
- create EC2 instance, RDS instance and Network/Application Load Balancer in AWS, wait for them to be in a running state
- let Workload Discovery on AWS discover them
- import them to a new diagram
- observe

**Expected behavior**
EC2, RDS, LB instances should not have a ⚠️ icon on the top-right corner of their icons

**Screenshots**
![image](https://github.com/aws-solutions/workload-discovery-on-aws/assets/4004804/f3a091d4-6e45-44f7-bf04-1a459154d314)
![image](https://github.com/aws-solutions/workload-discovery-on-aws/assets/4004804/75a551c6-c2e3-4d96-ba12-ca9e05152f13)
![image](https://github.com/aws-solutions/workload-discovery-on-aws/assets/4004804/7980c014-ca49-4f26-ab40-425d8d8e5aba)


**Browser (please complete the following information):**

- Name: Chrome
- Version: 118.0.5993.117 (Official Build) (arm64)

**Additional context**
¯\_(ツ)_/¯

**Comment by svozza** [comment]
I dug into this an it looks like the frontend is expecting the state info for these resource types to be in a different field from the one that is being returned from the backend. Not too difficult to fix either. We will be aiming for a 2.1.3 release with this a few other bugfixes for the end of the year/early next year.

**Comment by svozza** [comment]
This issue has been fixed in v2.1.3 that was released yesterday.
