### ISSUE TITLE
Hosted Zone Icon not available

### ISSUE THREAD

**Issue by pedromonteiro18** [aws-solutions/workload-discovery-on-aws#485]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
The hosted zone icon is blank in the generated diagram

**To Reproduce**
Generate a diagram of any stack which has a hosted zone

**Expected behavior**
The icon to be visible

**Screenshots**
If applicable, add screenshots to help explain your problem.<img width="727" alt="Screenshot 2023-11-08 at 16 48 21" src="https://github.com/aws-solutions/workload-discovery-on-aws/assets/40637779/9d83d29b-aba0-4b8c-9e66-519f5e1dc424">
- Name [e.g. chrome, firefox] chrome
- Version [e.g. 22] Version 119.0.6045.105 (Official Build) (arm64)

**Additional context**

**Comment by svozza** [comment]
Yes, this is a bug. AWS Config are providing support for new resource types every month so we don't have the the icons for those new ones yet. We will add these icons in an upcoming patch release.

**Comment by svozza** [comment]
This issue has been fixed in v2.1.3 that was released yesterday.
