### ISSUE TITLE
Unable to export diagram to Diagrams.net

### ISSUE THREAD

**Issue by pedromonteiro18** [aws-solutions/workload-discovery-on-aws#486]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
Error when trying to export Diagrams.net diagram

**To Reproduce**
Generate a diagram. Try to export it. Export loads and then returns a popup error: 
```
lot
unsupported operand type(s) for *: 'NoneType' and 'float'

```

**Expected behavior**
To be able to export the diagram

**Screenshots**
<img width="1283" alt="image" src="https://github.com/aws-solutions/workload-discovery-on-aws/assets/40637779/79a9158f-7653-4ee3-b028-bc95f566c41b">

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox] chrome
- Version [e.g. 22] Version 119.0.6045.123 (Official Build) (arm64)

**Additional context**
This was working before I set up the cost reports. The cost reports have not loaded yet, but since then the exports have stopped working. Not sure if its related or not.

**Comment by svozza** [comment]
I'd be very surprised if this was related to the cost feature, they use completely different APIs. This issue has already been report and we are tracking it here: https://github.com/aws-solutions/workload-discovery-on-aws/issues/458. So I will close this one and post any updates there.
