### ISSUE TITLE
Resources not discovered

### ISSUE THREAD

**Issue by pedromonteiro18** [aws-solutions/workload-discovery-on-aws#487]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
I have deployed the global and regional stacks in each of the following accounts. Only the first account discovered the resources ~178. When I deployed the other accounts they only discovered an inline policy or two and nothing else. All accounts contain lambdas, which was discovered in the first account I imported but not the others. 

**To Reproduce**
Import multiple regions at once and deploy the global and regional stacks in each. 

**Expected behavior**
All resources not be found

**Screenshots**
<img width="1283" alt="Screenshot 2023-11-09 at 18 23 58" src="https://github.com/aws-solutions/workload-discovery-on-aws/assets/40637779/122ebc0a-8ad0-4946-bf61-f303274a9554">

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox] chrome
- Version [e.g. 22] Version 119.0.6045.123 (Official Build) (arm64)

**Comment by svozza** [comment]
I'll need the ECS logs described the [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html) ection to be able to diagnose what's happening here. Don't worry about getting the logs from the lambdas as mentioned in that doc, the ECS ones are the only ones that matter here.

**Comment by pedromonteiro18** [comment]
The link you provided takes me to the solutions overview

**Comment by pedromonteiro18** [comment]
If you're referring to the /ecs/workload-discovery-task logs I've attached them here.
[logs-insights-results(10).csv](https://github.com/aws-solutions/workload-discovery-on-aws/files/13312015/logs-insights-results.10.csv)

**Comment by svozza** [comment]
> The link you provided takes me to the solutions overview

Sorry my mistake, I've fixed the link.

**Comment by svozza** [comment]
Ah yes, this is a known issue:

`{"message":"Cannot read properties of undefined (reading'endpoint')","level":"error","timestamp":"2023-11-09T19:08:31.576Z"}`
If an item from Config has `null` in its `configuration` field then it causes a null pointer exception. We are planning to release a patch with a fix for this and several other issues in the next week or. I will ping you in this ticket when we have released

**Comment by pedromonteiro18** [comment]
Great, thank you very much.

**Comment by svozza** [comment]
This has been fixed in v2.1.2 that was released on Tuesday.
