### ISSUE TITLE
Comma in Service Name Results in Cost Feature sum of account to be 0

### ISSUE THREAD

**Issue by stroecri** [aws-solutions/workload-discovery-on-aws#489]
**Describe the bug**
We noticed the cost for certain accounts in the cost dashboard was 0 overall, but individual resources had a cost in the resources list on the same page; If we queried an account with a cost of 0 joint with an account with a cost of more than 0, the total cost for the two would become 0 too.

**To Reproduce**
1. Find a resource that has a comma in the name, for example: Contact Center Telecommunications (service sold by AMCS, LLC)
2. Create resource
3. onboard account with the specific region to WD
4. calculate cost for the account

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Browser (please complete the following information):**

- Name:  firefox
- Version 119.0 

**Additional context**
This is due to the comma in the iinput creating an extra column in the data, and then resulting in the cost column containing a string not a float.

**Comment by svozza** [comment]
Thank you for creating this issue. This appears to be down to how we are splitting the lines in the CSV file we get from S3: the extra comma causes an off by one error when we split on the `,` delimiter. We are working on a fix for it.

**Comment by svozza** [comment]
This issue has been fixed in v2.1.3 that was released yesterday.
