### ISSUE TITLE
"Load Cost" and "Cost Report" buttons are using different time spans by default, but showing the sameone in the UI

### ISSUE THREAD

**Issue by stroecri** [aws-solutions/workload-discovery-on-aws#490]
**Describe the bug**
When a user is navigating the diagram, and they want to calculate the cost of an architecture, the cost shown when clicking "load costs" is different from the cost shown in the cost report. The load costs button has a default time period of 1 month (the current month) but the information it shows is only for 5 days by default.

**To Reproduce**

1. Go to a diagram. Click on "calculate costs"
2. On the same diagram, after calculating costs, click on "Go to cost report"

**Expected behavior**
the two costs should be different, the one in the "load diagram" view always being lower than the one in the "cost report" view

**Screenshots**

**Browser (please complete the following information):**

- Name firefox
- Version 119.0

**Additional context**

**Comment by svozza** [comment]
Yes, this is a bug. On initial load the load cost button defaults to fix days but it should be reading it from the diagram settings panel.

**Comment by svozza** [comment]
This issue has been fixed in v2.1.3 that was released yesterday.
