### ISSUE TITLE
Cost does not update for certain accounts

### ISSUE THREAD

**Issue by stroecri** [aws-solutions/workload-discovery-on-aws#491]
**Describe the bug**
For just one account the cost just doesn't update at all after you click calculate; it just stays with the previous cost; but for the other accounts it works as expected. Inspecting the request found an error in the request response:

"errors": [
       {
           "path": [
               "getResourcesByCost",
               "costItems",
               3,
               "cost"
           ],
           "locations": null,
           "message": "Can't serialize value (/getResourcesByCost/costItems[3]/cost) : Expected type 'Float' but was 'String'."
       }

**To Reproduce**
I don't know exactly what produces it.

**Browser (please complete the following information):**

- Name firefox
- Version 120.0 

**Additional context**

**Comment by svozza** [comment]
Yes, this bug is related to #491 and how we parse services that have a comma in them. Luckily, the same fix that applied to that issue applies to this one.

**Comment by svozza** [comment]
This issue has been fixed in v2.1.3 that was released yesterday.
