### ISSUE TITLE
Customizable Dashboard

### ISSUE THREAD

**Issue by thebutler12** [aws-solutions/workload-discovery-on-aws#5]
We would build a new customizable dashboard feature. This will include an area that you can save frequently viewed architecture diagrams, metadata about resources of interest, cost data, and more. It will be displayed on log in, giving you quick access to the data that is important to you. We propose the following:

* A Dashboard page that you can customize with the data you want quick access to.
* Widgets for interesting metadata about your workloads.
* A space for saved diagrams, recently updated architecture diagrams.

**Comment by rakshb** [comment]
We've evaluated this request and added this to our backlog but it is not prioritized in the immediate roadmap for the solution.
