### ISSUE TITLE
Discovery not working with no logs

### ISSUE THREAD

**Issue by WCottrell4** [aws-solutions/workload-discovery-on-aws#503]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
A description of what the bug is.
The Discovery process is not working properly.  I have gone through the steps to import a new account, but nothing is coming through on Workload Discovery.  I have taken a look at the debugging suggestions, but I can not find any logs.  When looking at /esc/workload-discovery-cluster logs, there are no new logs, even though it seems as though the task is running every 15 minutes. 
**To Reproduce**

**Expected behavior**
A description of what you expected to happen.
I would expect there to be logs and for the discovery process to be functioning properly.
**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

Edge
lastest version

**Additional context**

**Comment by svozza** [comment]
You should be able to get to the log by finding the last stopped ECS task in the ECS console for the cluster named `workload-discovery-cluster`. If there are no stopped task then that means there is very likely some configuration issue (possibly an SCP) in your account that is preventing the task from launching.

<img width="1418" alt="Screenshot 2024-01-31 at 12 53 47" src="https://github.com/aws-solutions/workload-discovery-on-aws/assets/8573472/2e667985-a7e4-483a-9b56-d25278378da4">

**Comment by svozza** [comment]
You should be able to get to the log by finding the last stopped ECS task in the ECS console for the cluster named workload-discovery-cluster. If there are no stopped task then that means there is very likely some configuration issue (possibly an SCP) in your account that is preventing the task from launching.

<img width="1447" alt="Screenshot 2024-01-31 at 12 58 51" src="https://github.com/aws-solutions/workload-discovery-on-aws/assets/8573472/0c76654f-24cc-4bcb-9a4c-ff85adc9413e">

**Comment by WCottrell4** [comment]
Thank you for the help.  We found this yesterday and discovered the task was failing before it was completed, which is why there were no logs.  It was failing because the task security group was too restrictive for it to complete.

**Comment by WCottrell4** [comment]
We also had a 403 error when trying to view a diagram at first in the UI.  When looking at the Web ACL, we noticed the logging was disabled and once we enabled it, the diagrams worked perfectly.  Not sure why that would have caused a change, but that truly was the only change made for the diagrams to display as they should.  The tool is working properly now, so I need no further help.

**Comment by svozza** [comment]
It might have been that the `ApiAllowListedRanges` parameter had been changed. That parameter is for WAF but it only refers to the AppSync API not the UI. We need to clarify that more in the docs because it's caused issues for others too.

**Comment by WCottrell4** [comment]
Hello, I am running into an issue where I can not get diagrams to generate or expand randomly.  I am getting a 403 error at random times where the tool just stops working for an extended period of time and then will randomly begin working again.  Similar to the issue mentioned higher in this conversation chain, but it is not being resolved by any solutions that previously worked.  Any idea why this would happen?

**Comment by svozza** [comment]
Where are the 403 errors appearing? In the WebUI? What is the `ApiAllowListedRanges` CFN parameter that I mentioned earlier set to currently?

**Comment by WCottrell4** [comment]
The 403 is appearing in the UI and shown on the console as "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'reduce')".  There might also be another error in the console that is throwing, but the tool is working right now so I can't replicate the error at the moment

**Comment by WCottrell4** [comment]
The ApiAllowListedRanges in the parameters is set to the default, 0.0.00/1,128.0.0.0/1

**Comment by svozza** [comment]
Very odd. I've not seen this before. The next time it happens, try to see the network request to the `searchResources` GraphQL query. Does it look like this or is there a field called `errors` there instead of `resources`?

<img width="1423" alt="Screenshot 2024-02-13 at 17 15 46" src="https://github.com/aws-solutions/workload-discovery-on-aws/assets/8573472/97f00e8c-f641-48bf-a79b-db3c16964488">

**Comment by WCottrell4** [comment]
I have not recreated the error, but I was looking at that this morning when I was having the problem and it was showing 200 on all the calls the the GraphQL.
