### ISSUE TITLE
Cognito not allowing SAML IDP

### ISSUE THREAD

**Issue by WCottrell4** [aws-solutions/workload-discovery-on-aws#510]
**Describe the bug**
A description of what the bug is.
We are trying to set the Cognito to accept an Identity Provider instead of creating Cognito users for everyone we are hoping to have use this tool.  The SAML IDP is configured and we are getting successful logins in the external provider and new users created within the user pool.  However, Workload Discovery is keeping us on the login page and not letting us get any farther with the new user.  In many of the guides I found online to help configure this, I have seen a new button produced in the application login page giving the option to sign in with an external provider.  Is there a reason this does not appear in the Workload Discovery solution?

**To Reproduce**

Configure the Cognito identity provider,
Go to App Integration, into the app client
Hit View Hosted UI button
Get taken to login page and unable to go any farther.

**Expected behavior**
A description of what you expected to happen.
I would expect to be logged into the page.

**Browser (please complete the following information):**
Name: Edge & Chrome
Version: latest

- Name [e.g. chrome, firefox]

**Comment by svozza** [comment]
This requires a change in the UI to add a separate login workflow (there are other changes required but this is the main one). We have a plan to release SAML IDP integration in the next release but as of now, this is not a supported configuration.

**Comment by WCottrell4** [comment]
Thank you for the information.  Do you have any timeline for the next release to know when this will be available?

**Comment by mrpackethead** [comment]
Hi Just to add a +1 to this..  This is something that would be really useful to me.

**Comment by shujacks** [comment]
This has been fixed in v2.2.0. Closing the issue now.
