### ISSUE TITLE
Account Role Status Unknown

### ISSUE THREAD

**Issue by BQuinn-Assured** [aws-solutions/workload-discovery-on-aws#512]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

I have completed the above. Cluster health yellow but I am told that all single node clusters start in health yellow. 

**Describe the bug**
I do not know if my account and region will ever be discovered.

**To Reproduce**
Deployed Cloud Formation Template successfully 
Deployed Global Resource successfully
Deployed Regional Resource Successfully 
Selected Import from Form Account ID Name and Region selected 

Account Management shows:
Account Role Status: "Unknown" in Blue with i in circle sign
Account Last Discovered: "Awaiting Discovery" in Blue with i in circle sign
Region Resources: "Not Discovered" in Red with Bang in Triangle sign
None of these informational or warning messages provide any further detail.
**Expected behavior**
I expect My Region and Account to be discovered and/or to receive some indication of why they are not or when they first will be. 

**Screenshots**
![image](https://github.com/aws-solutions/workload-discovery-on-aws/assets/155664915/9ca62951-2b8b-4bea-9307-378f01d1061b)

**Browser (please complete the following information):**

- Chrome
- Version 121.0.6167.162 (Official Build) (64-bit)

**Additional context**
Deployed with the following non default configs in the Cloud formation Template 
NeptuneInstanceClass: db.serverless
OpensearchInstanceType: t3small.search
IPAllowListedRanges: <Contains a single /32>

**Comment by BQuinn-Assured** [comment]
`{
    "msg": "[{\"errorType\":\"WAFForbiddenException\",\"message\":\"403 Forbidden\"}]",
    "stack": "Error: [{\"errorType\":\"WAFForbiddenException\",\"message\":\"403 Forbidden\"}]\n    at /code/src/lib/apiClient/appSync.js:57:33\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.getAccounts (/code/src/lib/utils.js:174:24)\n    at async Promise.all (index 0)\n    at async discoverResources (/code/src/lib/index.js:19:69)\n    at async discover (/code/src/index.js:14:3)",
    "level": "error",
    "message": "Error in Discovery process.",
    "timestamp": "2024-02-17T19:31:31.667Z"
}`

**Comment by svozza** [comment]
The issue is the the `ApiAllowListedRanges` value. It is not used to control access to the UI, it is only for accessing the AppSync API. The discovery process needs to be able to access it so if you set that value that stops tasks in the private subnet being able to access the API you will see that error. Set the parameter back to the default value (`0.0.0.0/1,128.0.0.0/1`) and the process will start running again. I realise the parameter is confusing and I am going to remove it in the next release.
