### ISSUE TITLE
Lambda Node.js 16 EOL on June 12th, 2024

### ISSUE THREAD

**Issue by psjd23** [aws-solutions/workload-discovery-on-aws#517]
AWS has notified me that NodeJS 16.x support ends on 2024-06-12. This may eventually lead to security vulnerabilities.

Currently the AthenaGlu-AWSCURInitializer and Sea-OpenSearchSetupFunction both use 16.x. 

https://github.com/aws-solutions/workload-discovery-on-aws/blob/91e36ffb4c3417f9c4d4a1f6da278b5e3b26ea4e/source/cfn/templates/search-resolvers.template#L82
https://github.com/aws-solutions/workload-discovery-on-aws/blob/91e36ffb4c3417f9c4d4a1f6da278b5e3b26ea4e/source/cfn/templates/athena-glue-crawler.template#L152

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy:~:text=Amazon%20Linux%202-,Jun%2012%2C%202024,-Jul%2015%2C%202024

**Comment by svozza** [comment]
This will be updated in the upcoming v2.2.0b release.

**Comment by svozza** [comment]
We have released this as part of the 2.1.7 patch release instead.
