### ISSUE TITLE
Migrate AWS SDK for JavaScript v2 APIs to v3

### ISSUE THREAD

**Issue by trivikr** [aws-solutions/workload-discovery-on-aws#523]
**Feature name**
Migrate AWS SDK for JavaScript v2 APIs to v3.

**Is your feature request related to a problem? Please describe.**

AWS SDK for JavaScript v2 will enter maintenance mode on September 8, 2024 and reach end-of-support on September 8, 2025. For more information, check blog post at https://a.co/cUPnyil

The workload-discovery-on-aws makes calls using AWS SDK for JavaScript v2 at many places
https://github.com/search?q=repo%3Aaws-solutions%2Fworkload-discovery-on-aws%20%27aws-sdk%27&type=code

**Describe the feature you'd like to see implemented**

Migrate AWS SDK for JavaScript v2 APIs to v3.

**Describe the value this feature will add to AWS Perspective**

It'll be using the supported AWS SDK for JavaScript

**Describe alternatives you've considered**
N/A

**Comment by trivikr** [comment]
Example migration PR: https://github.com/aws-solutions/workload-discovery-on-aws/pull/415

**Comment by trivikr** [comment]
New PR to migration AWS SDK for JavaScript APIs to v3 in cur-notification: https://github.com/aws-solutions/workload-discovery-on-aws/pull/524

**Comment by ConnorKirk** [comment]
All the remaining uses of the v2 SDKs will be migrated to v3 in the next release
