### ISSUE TITLE
Deployment to New AWS Account fails due to default Lambda Concurrent Executions limits

### ISSUE THREAD

**Issue by jwalls89** [aws-solutions/workload-discovery-on-aws#536]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
Deployment to AWS Account fails due to **Lambda Concurrent executions** quota being insufficient due to the CFN templates needing close to 200 reserved concurrency slots.  As new accounts appear to be restricted to 10 **Lambda Concurrent executions** by default (see https://repost.aws/questions/QU7NV9YgI3RGaqVOFdrZYnSQ/concurrency-limits-for-lambda-does-not-allow-to-reserve) , this solution will never deploy successful for someone like myself trying it out on a personal account without taking remediating action first (i.e. requesting service quota increase)

As this error could also happen in account with insufficient spare reserved capacity suggest it would be helpful if the deploy pre-requistes documentation had a check for the amount of reserved concurrency available in the region being deployed to.

**To Reproduce**

1. Deploy solution to a new AWS account.
2. Stack deployment fails when reserved concurrency for Lambda requested by a template.  In my case feel over on the workload-discovery-GremlinResolversStack about 20 mins into deployment.  Apologies for not having the exact error to hand but the substack got rolled back.  

**Expected behavior**
Deploy prerequistes documentation update reduces the chances of hitting the area and makes explicit (without reading all the templates) the Lambda capacity requirements of the solution.

**Comment by svozza** [comment]
I agree that we should document that the solution uses these concurrent executions although I'm wondering if it makes more sense for this to live in the quotas section of the documentation: https://docs.aws.amazon.com/solutions/latest/workload-discovery-on-aws/quotas.html.

**Comment by svozza** [comment]
We have updated the documentation in the quotas section to note this limit: https://docs.aws.amazon.com/solutions/latest/workload-discovery-on-aws/quotas.html
