### ISSUE TITLE
Plot EC2 instance info on graphs

### ISSUE THREAD

**Issue by jdpnlapperry1** [aws-solutions/workload-discovery-on-aws#55]
**Feature name**
AWS Perspectives Resource Metadata

**Is your feature request related to a problem? Please describe.**
Customers would like to have the diagram include instance type information to aid in more detailed documentation.

**Describe the feature you'd like to see implemented**
The ability to overlay resource metadata on the graph to aid in developing documentation.

**Describe the value this feature will add to AWS Perspective**
The ability to create more complete documentation.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by svozza** [comment]
Thanks for this request, I like this idea.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
