### ISSUE TITLE
Hide all resources of a particular type on a diagram.

### ISSUE THREAD

**Issue by chris-armstrong** [aws-solutions/workload-discovery-on-aws#551]
**Feature name**
Hide all resources of a particular type on a diagram.

**Is your feature request related to a problem? Please describe.**
I'm constructing diagrams with lots of serverless resources such as Lambda functions. However, these
types of resources can have a lot of default relationships such as tags, roles, VPCs, etc., so visualising them
 with all their relationships can result in a very clutered diagram and lots of lines going from the resource
to a role or tag, which is unhelpful.

**Describe the feature you'd like to see implemented**
* Ability to hide all resources of a particular type on a diagram to reduce clutter
* Set defaults about which resource relationships are hidden on a diagram by default
* Automatically hide lower

**Describe the value this feature will add to AWS Perspective**
Improve the usability of AWS Workload Discovery when working with serverless architectures.

**Describe alternatives you've considered**
I can use the `Actions->Resources->Remove` menu, but this is tedious when working
with lots of diagrams and not easily accessed. It could be surfaced as a toolbar button
instead of a menu item.

**Additional context**

**Comment by svozza** [comment]
You can exlcude resource types from a diagram in the Daigram Settings section on the Diagram page. Is this the functionality you're talking about?

<img width="1082" alt="Screenshot 2024-09-30 at 11 07 18" src="https://github.com/user-attachments/assets/440f81dc-8bca-4dc3-ae8e-bfa635a95563">

**Comment by chris-armstrong** [comment]
This setting lets you specify resources to include, but using this as a discovery tool for my architecture, I'm more interested in explicitly excluding resources which clutter the diagram (such as tags and roles), and possibly being able to do this as a default setting or some kind of diagram settings profile to apply

**Comment by svozza** [comment]
You can do both, the **Filter Type** toggle determines whether the resource types selected in the **Resource Types** dropdown will be excluded (**Hide Selected**) or included (**Only Show Selected**). When you more expand more resources in the diagram, any newly added resources types will be excluded/included as per your selection.

https://github.com/user-attachments/assets/3abad4ba-0e56-437f-8c25-40afbe209868

**Comment by chris-armstrong** [comment]
Thanks, sorry I missed this one

**Comment by chris-armstrong** [comment]
closing
