### ISSUE TITLE
Import accounts from AWS Organizations

### ISSUE THREAD

**Issue by philippegabert** [aws-solutions/workload-discovery-on-aws#566]
**Feature name**
AWS Organizations import 

**Describe the feature you'd like to see implemented**
Instead of importing the list of accounts through a form or through a CSV, it would be great if it was possible to import it from AWS Organizations and, ideally, import (or not) new accounts automatically when they are added to organisations.

**Describe the value this feature will add to AWS Perspective**
Less manual operations for end users.

**Describe alternatives you've considered**
Export accounts from AWS Organizations into a CSV file, then import of the CSV file.

**Comment by svozza** [comment]
if you deploy Workload Discovery in AWS Organization mode you shouldn't need to import the accounts through the UI:

https://docs.aws.amazon.com/solutions/latest/workload-discovery-on-aws/aws-organizations-account-discovery-mode.html

**Comment by philippegabert** [comment]
Oohh ! I missed this. Thanks a lot !

**Comment by svozza** [comment]
Forgot to mention, when deploying in an org you need to deploy to a delegated admin account, more info here on the capabilities the account needs:

https://docs.aws.amazon.com/solutions/latest/workload-discovery-on-aws/choosing-the-deployment-account.html
