### ISSUE TITLE
AWS SSO - SAML IdP integration

### ISSUE THREAD

**Issue by rotmi** [aws-solutions/workload-discovery-on-aws#61]
**Feature name**
AWS SSO - SAML IdP integration

**Describe the feature you'd like to see implemented**
As a customer I would like to have my current SSO setup with AWS SSO - SAML IdP supported by AWS Perspective so that the users don't have to recognise multiple passwords

**Describe the value this feature will add to AWS Perspective**
Convenience and integration in the current SSO setup

**Comment by ConnorKirk** [comment]
Thanks for the suggestion @rotmi 👍 We will keep this in mind. I agree it would be a useful addition

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog and has been prioritised on the roadmap for the solution.
