### ISSUE TITLE
RBAC support via AWS IAM roles

### ISSUE THREAD

**Issue by rotmi** [aws-solutions/workload-discovery-on-aws#62]
**Feature name**
RBAC support via AWS IAM roles

**Describe the feature you'd like to see implemented**
As a customer I would like to control who can view what workload within AWS Perspective depending e.g. on AWS IAM roles so that not everybody has view on everything.

**Describe the value this feature will add to AWS Perspective**
More fine granular control of permissions to view workloads within AWS Perspective

**Comment by svozza** [comment]
This is something that's come up with other customers too, the fine grained permissions this would allow would definitely be very useful.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog and has been prioritised on the roadmap for the solution.
