### ISSUE TITLE
Extensibility with non AWS resource information

### ISSUE THREAD

**Issue by oli99sc** [aws-solutions/workload-discovery-on-aws#63]
**Feature name**
Above and beyond AWS infrastructure, providing a "Big Picture" view on your service landscape from business to infrastructure. Connecting all the things!

**Is your feature request related to a problem? Please describe.**
We envision a big picture of our landscape connecting a business perspective view (capability, product, service) with the infrastructural view. So ideally it should be possible to connect the different views in the graph representation and make it accessible for search and graph analysis. 
Specifically we currently think about:
 - information from our git repositories 
 - information from our oAuth servier connecting client scopes and resource servers
 - Business Architecture (owned business entities, provided APIs etc) 

**Describe the feature you'd like to see implemented**
Allow customers to add information for additional node and link types into the graph via API from external sources.
Make these types searchable and allow visualization. 
Allow use of AWS resources tags when creating links between AWS resources and external data.

**Describe the value this feature will add to AWS Perspective**
This will allow perspective to develop into a tool where business and tech together can rationalize about the overall solution architecture. (see #7 ) 

**Describe alternatives you've considered**
Buiding our own "Big Picture" model and visualization, or use tools like ardoq.com instead. 

**Additional context**
![Bildschirmfoto 2020-10-12 um 14 35 10](https://user-images.githubusercontent.com/394961/95747139-36ddcd00-0c98-11eb-8454-566f0c3af4da.png)

**Comment by svozza** [comment]
Thank you so much for the detailed feature request, this is really good.

**Comment by oli99sc** [comment]
Would be great to know, if this is anything you could imagine to develop the perspective solution into?
