### ISSUE TITLE
tabbed diagram

### ISSUE THREAD

**Issue by rasisuku** [aws-solutions/workload-discovery-on-aws#65]
**Feature name**
tabbed diagram

**Is your feature request related to a problem? Please describe.**
tabbed diagram provide easy way to quickly create/switch diagrams

**Describe the feature you'd like to see implemented**
Looking for feature where in we can create diagrams in multiple tabs.

**Describe the value this feature will add to AWS Perspective**
Tell us how this feature might improve AWS Perspective.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by svozza** [comment]
We've had this suggestion a few times and I really like it, it's definitely going on our backlog.
