### ISSUE TITLE
Region / Account integration API

### ISSUE THREAD

**Issue by mmoltenb** [aws-solutions/workload-discovery-on-aws#66]
**Feature name**
Region / Account integration API

**Is your feature request related to a problem? Please describe.**
The good practice setup of an AWS Organization includes a multi-account configuration (e.g. by business unit or larger business application). If you have more than a handful of accounts and regions per account, the import of the accounts and regions using the provide web interface requires a lot of time to maintain and each time an account is provisioned automatically (e.g. using Landing Zone Solution or Control Tower) and manual steps are necessary

**Describe the feature you'd like to see implemented**
Implement an AWS Perspective API that allows programmatic creation and management of integrated accounts and region to:
- Import data to AWS Perspective
- Deploy the account / region related CFN template 

**Describe the value this feature will add to AWS Perspective**
Increase acceptance for usage in larger organizations and accounts

**Describe alternatives you've considered**
-

**Additional context**
Think of customers having 200+ accounts with more than one region enabled and planning to use AWS Perspective centrally.

**Comment by svozza** [comment]
Yes, I like this idea a lot.

**Comment by ConnorKirk** [comment]
Note: This aims to solve a similar problem to #1

**Comment by ayelurigithub** [comment]
This would be a great feature to have. 
I have a similar req., so that Account Vending Machine could automatically trigger the AWS Perspective account addition, instead of we manually doing it.

**Comment by svozza** [comment]
These APIs will be be implemented when we build #11 so we will track that in the main  issue.
