### ISSUE TITLE
Scheduled Reports and Diagrams

### ISSUE THREAD

**Issue by dunn-systems** [aws-solutions/workload-discovery-on-aws#68]
**Feature name**
Scheduled Reports and Diagrams

**Describe the feature you'd like to see implemented**
I would like to be able to navigate through the console to be able setup scheduled reports to be able to output to s3 or dynamodb.  I would like to be able to [build my own query](https://github.com/awslabs/aws-perspective/issues/6) and then to have that query delivered to s3 or dynamodb based on an admin defined schedule (daily, weekly, monthly).  In the export options I would like to be able to specify through a multi-select option for the diagram output (draw.io, jpg, png, bmp) and raw data output formats (yaml, json, csv)

**Describe the value this feature will add to AWS Perspective**
This would enable Perspective to provide ETL service and data to other systems in a de-coupled architecture with systems such as Splunk.  The diagrams could be added to Splunk dashboards along with the relevant data to provide enrichments.

**Additional context**
Beyond Splunk, the data potentially collected by perspective is a number of views combined from some quantity of accounts and regions, where I really seeing Perspective being a potentially symbiotic service with [AWS Organizations](https://github.com/awslabs/aws-perspective/issues/1), where if I could go into my companies organization and [build my own queries](https://github.com/awslabs/aws-perspective/issues/6) that are then scheduled to be output to various locations, then I could move on to figuring out how to integrate perspective with my [companies saml idp](https://github.com/awslabs/aws-perspective/issues/61) as well as the down stream [RBAC definitions](https://github.com/awslabs/aws-perspective/issues/62) that I will need to ensure that Account owner A can only view data about their account(s), while Account owner B can only view data about their account(s).

**Comment by svozza** [comment]
Thanks for the detailed issue, I really like how these different enhancements can all work together.

**Comment by svozza** [comment]
We've evaluated this request and added it to our backlog but it is not prioritised in the immediate roadmap for the solution.
