### ISSUE TITLE
Include business overlay 

### ISSUE THREAD

**Issue by fsam437** [aws-solutions/workload-discovery-on-aws#7]
Overlay/addition of business information to display project team, business units utilising projects/resources, apps to enrich the network diagram.

This would enable business analysts and management etc to work more closely with technical staff understand resource utilisation or any change management issues.  Would also help to identify points of contact across the org

**Comment by oli99sc** [comment]
This enhancement would also be interesting for us.

**Comment by svozza** [comment]
I recommend using the 👍 reaction to upvote this suggestion as it helps us get an idea of how popular certain feature requests are.

**Comment by rakshb** [comment]
We've evaluated this request and added this to our backlog but it is not prioritized in the immediate roadmap for the solution.
