### ISSUE TITLE
Time Series Capability

### ISSUE THREAD

**Issue by dbrhee** [aws-solutions/workload-discovery-on-aws#70]
**Feature name**
Time Series Capability as inventory is fluid and changes. 

**Is your feature request related to a problem? Please describe.**
A description of what the problem is.

**Describe the feature you'd like to see implemented**
Time Series dial on the diagram that you could scroll forward and backward to see changes in the inventory.

**Describe the value this feature will add to AWS Perspective**
One use case is the capability to look at forensic analysis when resources are spun up (due to an event like an account compromise) and see it historically for mitigative action. 

**Describe alternatives you've considered**
None at this time

**Comment by svozza** [comment]
Yes, this is definitely something we want to do in future versions, as Perspective only does a soft delete the data we need is in the DB already so we've got the foundations for the feature already.

**Comment by svozza** [comment]
The architecture of v2.0.0 has changed significantly and we can't support this use case with the new data model.
