### ISSUE TITLE
Support for EKS Resources

### ISSUE THREAD

**Issue by zhujik** [aws-solutions/workload-discovery-on-aws#72]
**Feature name**
EKS Support

**Is your feature request related to a problem? Please describe.**
The problem is that AWS Perspective does not give insights about the EKS architecture in AWS.

**Describe the feature you'd like to see implemented**
EKS clusters, VPCs, EC2 Instances, NodeGroups etc. displayed in a nice manner.

**Describe the value this feature will add to AWS Perspective**
To be able to provide EKS architecture diagrams.

**Describe alternatives you've considered**
Manually putting everything together.

**Additional context**
None

**Comment by svozza** [comment]
Thanks for this, several other customers have been looking for EKS support too.

**Comment by svozza** [comment]
v2.0.0 of Workload Discovery supports EKS clusters now. Note though, that we only find the relationships that are AWS specific, e.g., NodeGroups, Autoscaling Groups, EC2 Instances, Security Groups etc not for example the pods running inside the cluster as this requires `kubectrl` access.
