### ISSUE TITLE
Visualize NACLs and SGs

### ISSUE THREAD

**Issue by trescos** [aws-solutions/workload-discovery-on-aws#80]
**Feature Name**
Give your feature a name.
-- Security Visualizer

**Is your feature request related to a problem? Please describe.**
A description of what the problem is.
-- An ES customer is struggling with control of their security environment. As they grow it is becoming more and more difficult for them to visualize what their NACLs and SGs are actually doing in their environment. 

**Describe the feature you'd like to see implemented**
A description of what you would like to see.
-- Visual mapping of NACLs and SGs.

**Describe the value this feature will add to AWS Perspective**
Tell us how this feature might improve AWS Perspective.
-- Users will be able to troubleshoot communications issues at a glance.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**
Add any context or screenshots about the feature request here.

**Comment by svozza** [comment]
I could see this being very useful!

**Comment by rakshb** [comment]
We evaluated this request and it is not prioritized in the immediate roadmap for the solution.
