### ISSUE TITLE
Add Name or Labels to table of Account ID and Region

### ISSUE THREAD

**Issue by bcdady** [aws-solutions/workload-discovery-on-aws#82]
**Feature name**
Sector Names

**Is your feature request related to a problem? Please describe.**
There is no field to provide a custom name or label to each combination of Account ID  and Region. So if/when a Perspective user Imports multiple Regions across multiple Accounts, they must memorize or maintain a separate cross-reference of each Account ID. Additionally, the class of sets of accounts and regions does not have a name. Therefore it is difficult to specify a unique name to refer to each instance/combination by.

**Describe the feature you'd like to see implemented**
Each item in a table of accounts and regions should be referred to as a Sector, and each Sector should have a unique name. A sector name could start as basic as {account-id}-{region}, but ideally the Perspective user could provide an arbitrary name like TestAccount-OR, or ServiceName-Prod1.

**Describe the value this feature will add to AWS Perspective**
Providing a Name or Label field for each sector will greatly improve the user experience for Perspective users with multiple Accounts and/or regions, by rasing the cognitive burden of correlating which Sector in the list contains which business functions and/or resources.

**Describe alternatives you've considered**
The most important part of this request is the ability to add a custom Name or Label to each entry in the table of "Accounts & Regions". It is less important to me what this solution "Feature" is named. Instead of "Sector", each set of account ID and region could also be called a "set", or compartment.

**Comment by svozza** [comment]
This is a great suggestion.

**Comment by svozza** [comment]
This feature was added in v1.1.0.
