### ISSUE TITLE
Add Pagination to the API

### ISSUE THREAD

**Issue by ConnorKirk** [aws-solutions/workload-discovery-on-aws#87]
**Is your feature request related to a problem? Please describe.**
Responses from the Lambda may be too large. Adding pagination to the API will overcome this issue.

**Comment by rsiripan** [comment]
I have noticed that V2 or version 1.0.1 has been released, is this new version address the above issue as well?

**Comment by svozza** [comment]
No, pagination was not present in that version, you can see the changes in `1.0.1` here:

https://github.com/awslabs/aws-perspective/blob/master/CHANGELOG.md

**Comment by svozza** [comment]
This was delivered in v2.0.0.
