### ISSUE TITLE
SNS subscriptions

### ISSUE THREAD

**Issue by s12v** [aws-solutions/workload-discovery-on-aws#96]
**Feature name**
SNS subscriptions

**Describe the feature you'd like to see implemented**
I would like to visualise SNS subscriptions as connections between SNS topics and corresponding resources (e.g. SQS queues or lambdas)

**Describe the value this feature will add to AWS Perspective**
SNS subscriptions provide insights on data flow and dependencies. It would be interesting to see a visualisation.

I'm trying to figure out how to implement it in the code. My thought is to scan all SNS subscriptions in each account, and then correlate with SNS topics and other related sources (that I can take from Neptune).

It looks like that resources are discovered via AWS Config. `importAwsConfig()` calls `DiscoveryService.findRelationships()` which has a list of `resourcesToScan[]`. However, `AWS::SNS::Topic` resource type is not there. So, how do they even appear in Perspective now? Could you please explain how does the discovery component work?

It would be also interesting to run the discovery application locally, is that possible? I guess Neptune is not available outside of VPC?

**Comment by svozza** [comment]
Hi there, apologies for the late reply, the reason why I'm holding off is that I'm looking to refactor this code (it's some of the oldest in the code base) to reduce the amount of calls we make to config so I don't want give you information that will be out of date soon.

**Comment by svozza** [comment]
SNS subscriptions were added in v2.0.0.
